// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiVcKkRsBNii8wEuK1zGiiunPntww7Xkk',
    appId: '1:793819999155:web:5270bfbef8af0ff86af9c6',
    messagingSenderId: '793819999155',
    projectId: 'emdy-chat',
    authDomain: 'emdy-chat.firebaseapp.com',
    storageBucket: 'emdy-chat.appspot.com',
    measurementId: 'G-BYZS56P2PT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ0yqtjX7ur6K3fI9UX_ST88eu7Zrfi5M',
    appId: '1:793819999155:android:53a0bfbf844c35716af9c6',
    messagingSenderId: '793819999155',
    projectId: 'emdy-chat',
    storageBucket: 'emdy-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9G1C0E8D61AVk3jrDAK1g9t6jZ-Tg0Rw',
    appId: '1:793819999155:ios:a862bea15c59c9b76af9c6',
    messagingSenderId: '793819999155',
    projectId: 'emdy-chat',
    storageBucket: 'emdy-chat.appspot.com',
    iosClientId: '793819999155-ovpkaae8sji2dap5qm47jpv7eclv569m.apps.googleusercontent.com',
    iosBundleId: 'com.example.emdyChat',
  );
}
